### ISSUE TITLE
GITBOOK的文章都看不了

### ISSUE THREAD

**Issue by linchuche** [feelschaotic/AndroidKnowledgeSystem#1]
![image](https://user-images.githubusercontent.com/9493593/53478432-c3328080-3ab1-11e9-8d11-0ba08902abf4.png)
是没有文章还是出了问题吗

**Comment by feelschaotic** [comment]
你好，这个情况是因为没有文章，目前知识体系脑图更新情况如下：

0. 方向/移动端开发的未来方向
2. 架构能力/设计模式
3. 开源库/关于开源库一些想说的话
3. 开源库/网络/Retrofit
3. 开源库/依赖注入/ButterKnife
7. 进阶/动态化/聊聊移动端的动态化之路
7. 进阶/动态化/混合开发/JavaScript引擎
7. 进阶/动态化/热修复
7. 进阶/AOP/AOP
10. T型成长/团队管理/代码质量与代码规范

具体的更新情况可以查看目录文件SUMMARY.md
其他知识点还在陆续更新中，欢迎关注。

![](https://user-images.githubusercontent.com/23227460/53493272-f424ac80-3ad5-11e9-85e9-b21f8aefbe07.png)

**Comment by linchuche** [comment]
好的谢谢
