### ISSUE TITLE
好多内容都是空的？？？？

### ISSUE THREAD

**Issue by yangzhanlong** [feelschaotic/AndroidKnowledgeSystem#2]

**Comment by Omooo** [comment]
是的呢，不过作者可能有点忙鸭～
阔步至此的打下广告～
https://github.com/Omooo/Android-Notes
（逃

**Comment by feelschaotic** [comment]
目前知识体系脑图更新情况如下：

1. 方向/移动端开发的未来方向
2. 架构能力/设计模式
3. 开源库/关于开源库一些想说的话
4. 开源库/网络/Retrofit
5. 开源库/依赖注入/ButterKnife
6. 进阶/动态化/聊聊移动端的动态化之路
7. 进阶/动态化/混合开发/JavaScript引擎
8. 进阶/动态化/热修复
9. 进阶/动态化/混合开发/布局引擎
10. 进阶/AOP/AOP
11. 系统源码/组件/WebView/JSBridge
12. T型成长/团队管理/代码质量与代码规范

其他知识点还在陆续更新中，欢迎关注。
个人精力有限，欢迎 pr 一起来维护这个项目。
