### ISSUE TITLE
是很久没更新了吗？

### ISSUE THREAD

**Issue by aqxuwenda** [feelschaotic/AndroidKnowledgeSystem#24]
是很久没更新了吗？我是在一家手机公司做Framework，如果需要的话可以提供一些机制原理的分析，顺便自己也能督促学习一下

**Comment by feelschaotic** [comment]
月初还有更新，手头比较忙，陆陆续续。

欢迎欢迎 🎉 ！

这里有份[维护指引](https://github.com/feelschaotic/AndroidKnowledgeSystem/wiki/%E7%BB%B4%E6%8A%A4%E5%8F%82%E4%B8%8E%E6%8C%87%E5%8D%97) ，可以在群里和小伙伴多多交流，或者私聊我，保持沟通。
