### ISSUE TITLE
授人以鱼不如授人以渔

### ISSUE THREAD

**Issue by Sumsear** [feelschaotic/AndroidKnowledgeSystem#3]
小姐姐其实可以写一些自己的学习方法，其实现在网上的资料非常丰富，但是学习起来不得要领，有些知识学完就忘，有些看的发际线后移到后脑勺都看不进去。其实学习知识很重要学习知识的能力更为重要，如果小姐姐能讲一下各个知识点的学习方法就更好了！

**Comment by feelschaotic** [comment]
感谢你的建议，我觉得非常好！

我之前在少部分的章节中有提到如何去掌握学习，比如开源库、JNI、Binder。接下来更新时，每个知识点我都会加入学习方法论，感谢建议。
